function IdentityTests(t)
    t.describe("Identity Tests", sub(t)
        t.beforeEach(sub(t)
            p = _InternalPurchases()
            p.configuration.configure({ apiKey: Constants().TEST_API_KEY })
            p.registry.clear()
            t.addContext({ purchases: p })
        end sub)

        t.it("Generates anonymous user ids", sub(t)
            t.assert.isTrue(t.purchases.isAnonymous(), "Expected anonymous user id")
            t.assert.isTrue(t.purchases.appUserId().startsWith("$RCAnonymousID:"), "Expected anonymous user id")
            t.pass()
        end sub)

        t.it("Logs in with app user id", sub(t)
            result = t.purchases.login("myappuserid")
            t.assert.isFalse(t.purchases.isAnonymous(), "Expected non-anonymous user id")
            t.assert.equal(t.purchases.appUserId(), "myappuserid", "Unexpected user id")

            t.assert.isValid(result, "Login result error")
            t.assert.isInvalid(result.error, "Unexpected error")
            assertSubscriberIsValid(t, result.data)
            t.pass()
        end sub)

        t.it("Log out generates new anonymous id", sub(t)
            t.assert.isTrue(t.purchases.isAnonymous(), "Expected anonymous user id")
            t.assert.isTrue(t.purchases.appUserId().startsWith("$RCAnonymousID:"), "Expected anonymous user id")
            initialAnonymousId = t.purchases.appUserId()
            t.purchases.login("myappuserid")
            t.assert.isFalse(t.purchases.isAnonymous(), "Expected non-anonymous user id")
            t.assert.equal(t.purchases.appUserId(), "myappuserid", "Unexpected user id")
            result = t.purchases.logout()

            t.assert.isTrue(t.purchases.isAnonymous(), "Expected anonymous user id")
            t.assert.isTrue(t.purchases.appUserId().startsWith("$RCAnonymousID:"), "Expected anonymous user id")
            t.assert.notEqual(t.purchases.appUserId(), initialAnonymousId, "Unexpected user id")

            t.assert.isValid(result, "Logout result error")
            t.assert.isInvalid(result.error, "Unexpected error")
            assertSubscriberIsValid(t, result.data)
            t.pass()
        end sub)
    end sub)
end function